language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "Mx6o+qXNdjuuDAnAFb73IMjeyb/CqAxwfB2w73ZnKcgy3ob82ZI4KkOrJPaQPtpuiv+fkfaeN/W+Ch4fJGWYmXnyUDhJWSYh0Nvero9iQYMnoPoiKwtHPNo1c+igP+ezm7iD2i7OfASc70RCawpjcsItpgv2XUgcfRw2XMjnQdz5QPJoFEH1y2MogwZLh2VEcKyRlHytJQpKw0zuyuGQsR0AQY/gx7ryH14svQRv75G8a5Logcl+UrBGKFs75eG8eCi0z7ZbQMLNW0hk228FBiWqdMERKNQSNFyJAT9F1guJyEibCNQNbAlxIch9KJdSR44yYgWU7kmtJW6Zh+uxkmUApu6E5ciJfX8x6xNow7Z6bbjOiPQYVPP5sbmW76P4AmtufvbZzJtTfS5KAmV20dsxoUhkW6/shubVyz+kp+2Z5jwf+ePSrQWxXxaLuSwaqPaP2/l3OgHmFhB5NqJG1DwB2sf52kzdAz3un3Rpe7ORZWvaeR62wmH6PNd11RRl0YO898rIohzEEqorlvLh2eG1+svI0gW6GbCxN3FbolCdxWh2uuXpKizfmr6JlBmnqO2DnfwkRJr9jra8J52RGf9Cu64MISXQLONeEocN7ktAf2VpJN1Rx1zMt2/oKE31zbdmnhRZmqHeqrP08FrsVTI00sFjgMBlQ77gnbMxBpA="
