name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "pdo, pdo_sqlite"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage-no-cache.xml"
        env:
          ENABLE_SECOND_LEVEL_CACHE: 0

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-sqlite-${{ matrix.php-version }}-${{ matrix.dbal-version }}-coverage"
          path: "coverage*.xml"
